// GENERATED by tauri-specta. Do not edit — see src-tauri/src/ipc/bindings.rs.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	startRecording: (input: StartRecordingInput) => typedError<null, AppError>(__TAURI_INVOKE("start_recording", { input })),
	stopRecording: () => typedError<null, AppError>(__TAURI_INVOKE("stop_recording")),
	cancelRecording: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_recording")),
	resumeRecording: () => typedError<null, AppError>(__TAURI_INVOKE("resume_recording")),
	getSessionState: () => typedError<SessionState, AppError>(__TAURI_INVOKE("get_session_state")),
	listHistory: (input: ListHistoryInput) => typedError<SessionSummary[], AppError>(__TAURI_INVOKE("list_history", { input })),
	searchHistory: (input: SearchHistoryInput) => typedError<SessionSummary[], AppError>(__TAURI_INVOKE("search_history", { input })),
	getHistoryEntry: (input: SessionIdInput) => typedError<SessionSummary, AppError>(__TAURI_INVOKE("get_history_entry", { input })),
	deleteHistoryEntry: (input: SessionIdInput) => typedError<null, AppError>(__TAURI_INVOKE("delete_history_entry", { input })),
	deleteHistoryEntries: (input: DeleteHistoryEntriesInput) => typedError<number, AppError>(__TAURI_INVOKE("delete_history_entries", { input })),
	/**  The privacy escape hatch. Deletes everything, immediately, with no tombstone. */
	clearHistory: () => typedError<number, AppError>(__TAURI_INVOKE("clear_history")),
	purgeHistory: (input: PurgeHistoryInput) => typedError<number, AppError>(__TAURI_INVOKE("purge_history", { input })),
	exportHistory: (input: ExportHistoryInput) => typedError<string, AppError>(__TAURI_INVOKE("export_history", { input })),
	/**
	 * 
	 *  * WHAT:  Shows a save dialog and writes the text to whatever the user picks.
	 *  * WHY:   Returns the chosen path, or None when the user cancelled. Cancelling
	 *  *        is NOT an error — treating it as one would make the UI apologise for
	 *  *        something the user deliberately did.
	 *  * WHERE: The History export flow.
	 *  
	 */
	saveTextFile: (input: SaveTextFileInput) => typedError<string | null, AppError>(__TAURI_INVOKE("save_text_file", { input })),
	getSettings: () => typedError<{ [key in string]: SettingValue }, AppError>(__TAURI_INVOKE("get_settings")),
	setSetting: (input: SetSettingInput) => typedError<null, AppError>(__TAURI_INVOKE("set_setting", { input })),
	resetSetting: (input: ResetSettingInput) => typedError<null, AppError>(__TAURI_INVOKE("reset_setting", { input })),
	/**
	 *
	 *  * WHAT:  The whole capability table, for the frontend to render from.
	 *  * WHY:   The frontend reads the SAME declarations the backend enforces. A
	 *  *        settings section becomes a map over these defs, so adding a setting is
	 *  *        a registry entry and never a new form component.
	 *  * WHERE: Called once by the Settings view and the dashboard shell.
	 *
	 */
	getRegistry: () => typedError<RegistrySnapshot, AppError>(__TAURI_INVOKE("get_registry")),
	listAppProfiles: () => typedError<AppProfile[], AppError>(__TAURI_INVOKE("list_app_profiles")),
	saveAppProfile: (input: SaveProfileInput) => typedError<null, AppError>(__TAURI_INVOKE("save_app_profile", { input })),
	deleteAppProfile: (input: DeleteProfileInput) => typedError<null, AppError>(__TAURI_INVOKE("delete_app_profile", { input })),
	getStats: () => typedError<StatsSummary, AppError>(__TAURI_INVOKE("get_stats")),
	listDictionary: () => typedError<DictionaryEntry[], AppError>(__TAURI_INVOKE("list_dictionary")),
	createDictionaryEntry: (input: CreateDictionaryEntryInput) => typedError<DictionaryId, AppError>(__TAURI_INVOKE("create_dictionary_entry", { input })),
	updateDictionaryEntry: (input: UpdateDictionaryEntryInput) => typedError<null, AppError>(__TAURI_INVOKE("update_dictionary_entry", { input })),
	deleteDictionaryEntry: (input: DeleteDictionaryEntryInput) => typedError<null, AppError>(__TAURI_INVOKE("delete_dictionary_entry", { input })),
	getEngineCapabilities: () => typedError<EngineCapabilities, AppError>(__TAURI_INVOKE("get_engine_capabilities")),
	listLanguages: () => typedError<LanguageOption[], AppError>(__TAURI_INVOKE("list_languages")),
	copyText: (input: CopyTextInput) => typedError<null, AppError>(__TAURI_INVOKE("copy_text", { input })),
	listModels: () => typedError<ModelReport[], AppError>(__TAURI_INVOKE("list_models")),
	getModelStatus: (input: ModelIdInput) => typedError<ModelReport, AppError>(__TAURI_INVOKE("get_model_status", { input })),
	downloadModel: (input: ModelIdInput) => typedError<string, AppError>(__TAURI_INVOKE("download_model", { input })),
	deleteModel: (input: ModelIdInput) => typedError<null, AppError>(__TAURI_INVOKE("delete_model", { input })),
	checkPermissions: () => typedError<PermissionReport[], AppError>(__TAURI_INVOKE("check_permissions")),
	requestPermission: (input: PermissionInput) => typedError<PermissionState, AppError>(__TAURI_INVOKE("request_permission", { input })),
	openPrivacyPane: (input: PermissionInput) => typedError<null, AppError>(__TAURI_INVOKE("open_privacy_pane", { input })),
	listInputDevices: () => typedError<DeviceInfo[], AppError>(__TAURI_INVOKE("list_input_devices")),
	openOnboardingWindow: () => typedError<null, AppError>(__TAURI_INVOKE("open_onboarding_window")),
	wipeAllData: () => typedError<WipeResult, AppError>(__TAURI_INVOKE("wipe_all_data")),
	checkForUpdate: () => typedError<UpdateCheck, AppError>(__TAURI_INVOKE("check_for_update")),
	installUpdate: () => typedError<null, AppError>(__TAURI_INVOKE("install_update")),
	checkReengagement: () => typedError<boolean, AppError>(__TAURI_INVOKE("check_reengagement")),
};

/** Events */
export const events = {
	audioLevelChanged: makeEvent<AudioLevelChanged>("audio-level-changed"),
	backtrackOccurred: makeEvent<BacktrackOccurred>("backtrack-occurred"),
	modelDownloadProgress: makeEvent<ModelDownloadProgress>("model-download-progress"),
	modelStateChanged: makeEvent<ModelStateChanged>("model-state-changed"),
	onboardingProgress: makeEvent<OnboardingProgress>("onboarding-progress"),
	partialTranscript: makeEvent<PartialTranscript>("partial-transcript"),
	permissionsChanged: makeEvent<PermissionsChanged>("permissions-changed"),
	sessionStateChanged: makeEvent<SessionStateChanged>("session-state-changed"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
	transcriptDelivered: makeEvent<TranscriptDelivered>("transcript-delivered"),
	updateAvailable: makeEvent<UpdateAvailable>("update-available"),
};

/* Types */
export type ActivityDay = {
	/**  Local date as YYYY-MM-DD. */
	date: string,
	session_count: number,
	word_count: number,
};

export type BacktrackOccurred = {
	message: string,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: AppError, AppResult
 *  * WHAT:  The only error type permitted to cross IPC.
 *  * WHY:   `recoverable` separates "this session is lost" from "this attempt
 *  *        failed" so the pill can decide between a red terminal state and a
 *  *        retry, without the frontend re-deriving that from the code. `detail`
 *  *        carries the underlying cause for the log file only — it is never shown
 *  *        to the user, because a raw sqlite or CoreAudio string is noise to them
 *  *        and a support burden to us.
 *  * WHERE: Returned by every command; constructed mostly through the helper
 *  *        constructors below and by the From impls at the bottom of this file.
 *  
 */
export type AppError = {
	code: ErrorCode,
	/**  Plain-language, user-facing, no jargon, no error numbers. */
	message: string,
	/**  False means the session or operation is over; true means try again. */
	recoverable: boolean,
	action: ErrorAction | null,
	/**  Underlying cause. Logged, never rendered. */
	detail: string | null,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: AppProfile
 *  * WHAT:  One application's overrides.
 *  * WHERE: Rendered in Settings; applied at session start.
 *  
 */
export type AppProfile = {
	/**  e.g. "com.apple.Terminal". Matched against the frontmost app. */
	bundle_id: string,
	display_name: string,
	/**  Sparse: only the settings this profile changes. */
	overrides: { [key in string]: SettingValue },
	enabled: boolean,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: AudioLevel
 *  * WHAT:  A windowed loudness sample for the pill's waveform.
 *  * WHY:   Computed on the drain thread rather than shipped as raw samples — the
 *  *        pill must not receive 16,000 floats a second, and it has a hard 60fps
 *  *        budget while inference is running.
 *  * WHERE: Emitted on the audio:level event; drawn by the Waveform component.
 *  
 */
export type AudioLevel = {
	rms: number | null,
	peak: number | null,
};

/**
 *  Waveform data. High frequency, and droppable by design — a missed frame is
 *  invisible, whereas queueing them would add latency to the thing being drawn.
 */
export type AudioLevelChanged = {
	level: AudioLevel,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: Capability
 *  * WHAT:  One feature of the app, completely described.
 *  * WHERE: The elements of registry::CAPABILITIES.
 *  
 */
export type Capability = {
	key: CapabilityKey,
	name: string,
	description: string,
	settings: SettingDef[],
	/**
	 *  OS grants required before any command on this capability may run. The
	 *  command factory enforces this — handlers never check permissions.
	 */
	requires: OsPermission[],
	engine_needs: EngineFeature[],
	nav: NavDef | null,
	metrics: MetricDef[],
	hotkey: HotkeyDef | null,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: CapabilityKey
 *  * WHAT:  The closed set of features the app has.
 *  * WHY:   An enum rather than a string, so a typo is a build error and so a new
 *  *        feature forces every exhaustive match to be revisited deliberately.
 *  * WHERE: The identity of every registry entry; carried on every IPC command so
 *  *        the factory knows which entry to preflight against.
 *  
 */
export type CapabilityKey = 
/**  The core loop: hotkey, record, transcribe, deliver. */
"DICTATION" | "HISTORY" | "STATS" | "DICTIONARY" | "MODELS" | "SETTINGS" | "ONBOARDING" | "UPDATES" | 
/**  A page that exists to say there is nothing to pay for. */
"BILLING";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: ChoiceSource
 *  * WHAT:  Where a dynamic setting's options come from.
 *  * WHY:   Input devices, installed models and supported languages cannot be
 *  *        listed in a static declaration — they depend on the machine, on what
 *  *        has been downloaded, and on which engine is selected. Naming the
 *  *        SOURCE keeps the setting declarative anyway: the registry still says
 *  *        what the control is, and the frontend resolves the options, so adding
 *  *        a device picker is still a registry entry rather than a bespoke form.
 *  * WHERE: Carried by SettingKind::DynamicChoice; resolved by the SettingControl
 *  *        component through the matching query command.
 *  
 */
export type ChoiceSource = "INPUT_DEVICES" | "MODELS" | 
/**
 *  Languages the SELECTED engine declares support for — which is what stops
 *  the UI offering Hindi on an engine that cannot speak it.
 */
"LANGUAGES";

export type CopyTextInput = {
	text: string,
};

export type CreateDictionaryEntryInput = {
	pattern: string,
	replacement: string,
	match_kind: MatchKind,
};

export type DeleteDictionaryEntryInput = {
	id: DictionaryId,
};

export type DeleteHistoryEntriesInput = {
	ids: SessionId[],
};

export type DeleteProfileInput = {
	bundle_id: string,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: DeliveryKind
 *  * WHAT:  Where the finished text actually landed.
 *  * WHY:   ClipboardOnly is a SUCCESS, not a failure — the app is fully useful
 *  *        without Accessibility permission, and treating the fallback as an
 *  *        error would nag a user whose setup is working as intended.
 *  * WHERE: Set by pipeline/deliver.rs; shown as a badge in History.
 *  
 */
export type DeliveryKind = 
/**  Clipboard written and synthetic paste accepted. */
"PASTED" | 
/**  Clipboard written; paste skipped or refused. Still a success. */
"CLIPBOARD_ONLY" | 
/**  Nothing was delivered. */
"NONE";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: DeviceInfo
 *  * WHAT:  One selectable input device as Settings lists it.
 *  * WHERE: Produced by the AudioSource port; rendered in Settings.
 *  
 */
export type DeviceInfo = {
	id: string,
	name: string,
	is_default: boolean,
	sample_rate: number,
	channels: number,
};

export type DictionaryEntry = {
	id: DictionaryId,
	/**  What the model tends to produce. */
	pattern: string,
	/**  What it should have been. Also fed to the engine as prompt vocabulary. */
	replacement: string,
	match_kind: MatchKind,
	enabled: boolean,
	/**
	 *  Bumped on use so the prompt builder can prioritise recent terms when the
	 *  dictionary is larger than the engine's prompt budget.
	 */
	used_at: number | null,
};

export type DictionaryId = number;

export type DownloadProgress = {
	model_id: ModelId,
	received_bytes: number,
	total_bytes: number,
	bytes_per_second: number,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: EngineCapabilities
 *  * WHAT:  One engine's self-declaration.
 *  * WHERE: Returned by every TranscriptionEngine implementation.
 *  
 */
export type EngineCapabilities = {
	id: EngineId,
	display_name: string,
	languages: LanguageSupport,
	features: EngineFeature[],
	/**  Measured on this machine, not taken from a datasheet. */
	realtime_factor: number | null,
	requires_download: boolean,
	runs_offline: boolean,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: EngineFeature
 *  * WHAT:  Optional abilities a capability entry can require of an engine.
 *  * WHERE: Declared per capability in registry/; matched against
 *  *        EngineCapabilities::features to gate UI.
 *  
 */
export type EngineFeature = 
/**  Can decode chunks during recording rather than only at the end. */
"STREAMING" | 
/**  Can detect the spoken language itself. */
"LANGUAGE_AUTO_DETECT" | 
/**
 *  Accepts a vocabulary prompt to bias recognition — what makes the custom
 *  dictionary improve recognition rather than only patch the output.
 */
"INITIAL_PROMPT" | 
/**  Runs with no network access at all. */
"OFFLINE";

export type EngineId = string;

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: ErrorAction
 *  * WHAT:  The one thing the UI can offer that would actually resolve the error.
 *  * WHY:   An error the user cannot act on is a dead end. Attaching the remedy to
 *  *        the error means the recovery affordance is decided once, next to the
 *  *        failure, instead of being re-derived by every screen that displays it.
 *  * WHERE: Optional field on AppError; rendered as the button in the error surface.
 *  
 */
export type ErrorAction = 
/**  Open a macOS privacy pane — the only recovery for a denied TCC grant. */
{ kind: "OPEN_PRIVACY_PANE"; pane: PrivacyPane } | 
/**  Jump to a section of our own settings, e.g. to rebind a clashing hotkey. */
{ kind: "OPEN_SETTINGS"; section: string } | 
/**  Offer to (re)download a model by id. */
{ kind: "DOWNLOAD_MODEL"; model_id: string } | 
/**  The operation is worth trying again as-is. */
{ kind: "RETRY" };

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: ErrorCode
 *  * WHAT:  The stable, exhaustive set of failure kinds the UI can distinguish.
 *  * WHY:   The frontend branches on this, never on message text. Adding a variant
 *  *        is a deliberate act that shows up as a non-exhaustive match in the
 *  *        TypeScript union, which is exactly the review we want.
 *  * WHERE: Carried on every AppError; mirrored to TypeScript by specta.
 *  
 */
export type ErrorCode = "MICROPHONE_DENIED" | "ACCESSIBILITY_DENIED" | 
/**
 *  The system dialog has just been put on screen and no answer has come
 *  back yet. Distinct from Denied, which means the user already said no.
 *  See AppError::microphone_pending.
 */
"MICROPHONE_PENDING" | "AUDIO_DEVICE_UNAVAILABLE" | "AUDIO_DEVICE_LOST" | 
/**
 *  The device opened and delivered pure silence — the capture path is
 *  broken rather than the room being quiet. See AppError::microphone_silent.
 */
"MICROPHONE_SILENT" | "AUDIO_FORMAT_UNSUPPORTED" | "MODEL_MISSING" | "MODEL_DOWNLOAD_FAILED" | "MODEL_CHECKSUM_MISMATCH" | "ENGINE_NOT_READY" | "ENGINE_UNSUPPORTED_LANGUAGE" | "TRANSCRIPTION_FAILED" | "SESSION_ALREADY_ACTIVE" | "SESSION_NOT_FOUND" | "ILLEGAL_TRANSITION" | "FINALIZE_TIMEOUT" | "SECURE_INPUT_ACTIVE" | "INJECTION_FAILED" | "CLIPBOARD_UNAVAILABLE" | "HOTKEY_CONFLICT" | "HOTKEY_REGISTRATION_FAILED" | "INVALID_INPUT" | "NOT_FOUND" | "DATABASE" | "IO" | "NETWORK" | "INTERNAL";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: export_history, ExportHistoryInput, ExportFormat,
 *  *   to_markdown, to_plaintext, to_csv
 *  * WHAT:  Serialises history to JSON, Markdown, CSV, or plain text and returns the
 *  *        content for the caller to save.
 *  * WHY:   It is the user's data and it stays that way — no lock-in was a stated
 *  *        non-negotiable, and an app that can only show you your transcripts has
 *  *        quietly become the only place they exist.
 *  *
 *  *        Returns the CONTENT rather than writing a file, so the save dialog
 *  *        stays where the user is and Rust never picks a path on their behalf.
 *  * WHERE: The export action in History.
 *  
 */
export type ExportFormat = "JSON" | "MARKDOWN" | "PLAIN_TEXT" | "CSV";

export type ExportHistoryInput = {
	format: ExportFormat,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: HotkeyBinding, KeyModifier
 *  * WHAT:  A global shortcut as the user bound it.
 *  * WHY:   Modelled rather than stored as a string like "Alt+Space" so conflict
 *  *        detection and the accelerator string are both derived from one shape,
 *  *        and a rebind cannot produce something unparseable.
 *  * WHERE: Stored as a setting; converted to a Tauri accelerator by the hotkey
 *  *        adapter; rendered by the Keycap component.
 *  
 */
export type HotkeyBinding = {
	modifiers: KeyModifier[],
	/**  Physical key name, e.g. "Space", "KeyD", "F13". */
	key: string,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: HotkeyDef
 *  * WHAT:  A global shortcut a capability binds, and its default.
 *  * WHY:   Declared here so conflict detection has one list to check against
 *  *        rather than discovering a clash at registration time, when the only
 *  *        available response is a failure the user cannot interpret.
 *  * WHERE: Read at startup by the hotkey adapter and by the rebind UI.
 *  
 */
export type HotkeyDef = {
	/**  Stable id, e.g. "dictation.toggle". */
	id: string,
	label: string,
	default: HotkeyBinding,
	/**  The setting key holding the user's override, if it is rebindable. */
	setting_key: string | null,
};

export type KeyModifier = "COMMAND" | "CONTROL" | "OPTION" | "SHIFT";

/**  A BCP-47-ish code as Whisper uses it: "en", "hi", "ar", "zh". */
export type LanguageCode = string;

export type LanguageCount = {
	language: string,
	session_count: number,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: LanguageOption
 *  * WHAT:  One entry in the language picker.
 *  * WHY:   `supported` travels with the option instead of the UI filtering the
 *  *        list, so a picker can SHOW an unavailable language greyed out with a
 *  *        reason rather than silently omitting it — a user who dictates in Hindi
 *  *        needs to know the engine is why it vanished.
 *  * WHERE: Returned by list_languages.
 *  
 */
export type LanguageOption = {
	code: string,
	/**  English name, for a UI in English. */
	label: string,
	/**  Whether the currently selected engine can transcribe it. */
	supported: boolean,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: LanguageSupport
 *  * WHAT:  Either every language the app knows, or an explicit set.
 *  * WHY:   `All` is not the same as a long list — Whisper genuinely covers 99
 *  *        languages and enumerating them at every call site would be noise, but
 *  *        Parakeet's omission of Hindi and Arabic must be a hard, checkable fact
 *  *        rather than a footnote.
 *  * WHERE: Part of EngineCapabilities; checked before a session starts.
 *  
 */
export type LanguageSupport = { kind: "ALL" } | { kind: "SET"; languages: LanguageCode[] };

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: LatencyStage
 *  * WHAT:  The stages of the stop-keypress-to-pasted-text path.
 *  * WHY:   Named separately from the background chunk decode, because only these
 *  *        are on the critical path — averaging the two together hides the number
 *  *        that actually matters.
 *  * WHERE: The `stage` column of session_metrics.
 *  
 */
export type LatencyStage = 
/**  Hotkey event to FSM transition. */
"HOTKEY_DISPATCH" | 
/**  CoreAudio device open — only paid in OnDemand capture mode. */
"DEVICE_OPEN" | 
/**  A background chunk decode. Off the critical path; recorded for context. */
"CHUNK_DECODE" | 
/**  The trailing fragment decode. The dominant term in the budget. */
"TAIL_DECODE" | 
/**  Segment join and seam de-duplication. */
"ASSEMBLE" | 
/**  The deterministic enhancement rules. */
"ENHANCE" | "CLIPBOARD_WRITE" | 
/**  Synthetic paste dispatch. */
"INJECT" | 
/**  Stop keypress to text on screen. The number the product promises. */
"TOTAL_FINALIZE";

export type LatencySummary = {
	stage: LatencyStage,
	p50_ms: number | null,
	p95_ms: number | null,
	sample_count: number,
};

export type ListHistoryInput = {
	limit: number,
	offset: number,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: MatchKind
 *  * WHAT:  How a dictionary pattern is matched against the transcript.
 *  * WHY:   Whole-word is the default because substring matching silently corrupts
 *  *        unrelated words — a replacement of "ai" would rewrite "said".
 *  * WHERE: On every DictionaryEntry.
 *  
 */
export type MatchKind = 
/**  Case-insensitive whole-word match. The default and the safe one. */
"WORD" | 
/**  Case-sensitive whole-word match. */
"WORD_CASE_SENSITIVE" | 
/**  Anywhere in the text. Powerful and easy to get wrong. */
"SUBSTRING";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: MetricDef
 *  * WHAT:  A latency stage a capability is expected to emit.
 *  * WHY:   Declaring metrics closes the loop in both directions: the dashboard
 *  *        cannot read a metric nothing writes, and nothing can write a metric
 *  *        that is never surfaced. Both of those are silent failures otherwise.
 *  * WHERE: Written by telemetry/latency.rs, read by services/stats.rs.
 *  
 */
export type MetricDef = {
	stage: LatencyStage,
	label: string,
	/**  Shown on the dashboard latency panel rather than kept for diagnostics. */
	user_facing: boolean,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: ModelDescriptor, ModelState, DownloadProgress
 *  * WHAT:  A downloadable model, its local status, and download progress.
 *  * WHY:   `sha256` is mandatory because a half-written model file passes an
 *  *        existence check and then fails deep inside inference, which is
 *  *        indistinguishable from a corrupt install. Verify by hash, never by
 *  *        presence.
 *  * WHERE: Listed by the ModelStore port; rendered by the model manager.
 *  
 */
export type ModelDescriptor = {
	id: ModelId,
	display_name: string,
	description: string,
	url: string,
	sha256: string,
	size_bytes: number,
	/**  Rough resident memory once loaded, so an 8GB machine can be warned. */
	approx_ram_mb: number,
	is_default: boolean,
};

export type ModelDownloadProgress = {
	progress: DownloadProgress,
};

export type ModelId = string;

export type ModelIdInput = {
	model_id: ModelId,
};

export type ModelReport = {
	descriptor: ModelDescriptor,
	state: ModelState,
	/**  Absolute path, present only once the file is hash-verified. */
	path: string | null,
};

export type ModelState = { kind: "NOT_DOWNLOADED" } | { kind: "DOWNLOADING"; received_bytes: number; total_bytes: number } | { kind: "VERIFYING" } | 
/**
 *  Downloaded and hash-verified, but the Neural Engine has not compiled it
 *  yet. That compile takes 15-60s once per machine and must never happen on
 *  the hotkey path.
 */
{ kind: "OPTIMIZING" } | { kind: "READY" } | { kind: "FAILED"; message: string };

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: ModelStateChanged
 *  * WHAT:  A model's state changed — typically the flip from Verifying to Ready.
 *  * WHY:   The state a model is in is decided in three places that are nowhere
 *  *        near the UI: a hash completing on the background prepare thread, a
 *  *        download installing, and a removal. `list_models` is a fetch-once, so
 *  *        without this the model manager renders whatever was true when it
 *  *        mounted and never learns otherwise.
 *  * WHERE: Emitted by adapters/http_models/store.rs through the EventSink port;
 *  *        consumed by the model manager and onboarding.
 *  
 */
export type ModelStateChanged = {
	model_id: ModelId,
	state: ModelState,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: NavDef
 *  * WHAT:  A capability's placement in the dashboard sidebar.
 *  * WHERE: Present means the capability appears in the nav; absent means it does
 *  *        not. Read by the dashboard shell.
 *  
 */
export type NavDef = {
	label: string,
	/**  Route segment, e.g. "history". Matched by the dashboard router. */
	route: string,
	/**  Lucide icon name. Resolved by the frontend. */
	icon: string,
	order: number,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: OnboardingProgress
 *  * WHAT:  Long-running first-run work, reported honestly.
 *  * WHY:   The Neural Engine compile takes 15-60 seconds once per machine, and a
 *  *        574MB download takes minutes. Both need real progress rather than an
 *  *        indeterminate spinner — a spinner on a multi-minute task reads as a
 *  *        hang, and this is the user's first impression of a "blazing fast" app.
 *  * WHERE: Emitted during onboarding and after any model switch.
 *  
 */
export type OnboardingProgress = {
	step: string,
	message: string,
	/**  0.0 to 1.0, or None when genuinely unknowable. */
	fraction: number | null,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: OsPermission
 *  * WHAT:  The OS grants a capability can require.
 *  * WHERE: Declared per capability in registry/; checked by the factory preflight.
 *  
 */
export type OsPermission = "MICROPHONE" | 
/**
 *  Required for synthetic keystrokes. Its absence degrades paste to
 *  clipboard-only; it never blocks recording.
 */
"ACCESSIBILITY";

/**
 *
 *  * SOURCE OF TRUTH KEYWORDS: PartialTranscript
 *  * WHAT:  Partial transcript preview text decoded from interior chunks while recording.
 *  * WHERE: Emitted by session/actor.rs; consumed by the pill overlay.
 *
 */
export type PartialTranscript = {
	text: string,
};

export type PermissionInput = {
	permission: OsPermission,
};

export type PermissionReport = {
	permission: OsPermission,
	state: PermissionState,
};

export type PermissionState = "GRANTED" | "DENIED" | 
/**  Never asked. The one state in which `request` will show a dialog. */
"NOT_DETERMINED";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: PermissionsChanged
 *  * WHAT:  The OS grants, pushed whenever one of them actually changes.
 *  * WHY:   A permission is granted in System Settings — a DIFFERENT app — and
 *  *        nothing in our process is told. The UI used to re-check on window
 *  *        focus, which is the obvious answer and is not enough: Murmur is an
 *  *        accessory app that often has no window on screen at all when the
 *  *        switch is flipped, and the operator reported the app never noticing
 *  *        even after quitting and relaunching.
 *  *
 *  *        Pushing it means the moment the switch moves, every window that cares
 *  *        is correct — no focus, no restart, no reopening a pane to "refresh"
 *  *        it. That last part is what he was actually complaining about.
 *  * WHERE: Emitted by the watcher in bootstrap; consumed by lib/use-permissions.
 *  
 */
export type PermissionsChanged = {
	reports: PermissionReport[],
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: PrivacyPane
 *  * WHAT:  The macOS System Settings privacy panes we deep-link into.
 *  * WHY:   A denied TCC permission cannot be re-prompted — the system dialog
 *  *        appears exactly once per bundle+signature. Deep-linking is the only
 *  *        recovery, so the pane is modelled rather than stringly-typed.
 *  * WHERE: Carried by ErrorAction::OpenPrivacyPane; resolved to an
 *  *        x-apple.systempreferences URL by the macOS adapter.
 *  
 */
export type PrivacyPane = "MICROPHONE" | "ACCESSIBILITY";

export type PurgeHistoryInput = {
	/**  0 means keep everything forever. */
	retention_days: number,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: RecordingMode
 *  * WHAT:  Whether the hotkey toggles recording or holds it.
 *  * WHY:   Push-to-talk changes the meaning of the key-up event, so it has to be
 *  *        known at session start rather than inferred later.
 *  * WHERE: Chosen in Settings, passed on the start command, read by the hotkey
 *  *        handler.
 *  
 */
export type RecordingMode = "TOGGLE" | "PUSH_TO_TALK";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: RegistrySnapshot
 *  * WHAT:  The whole table as one serialisable value for the frontend.
 *  * WHY:   The frontend reads the SAME declarations the backend enforces, rather
 *  *        than a mirror someone has to remember to update. That is what makes a
 *  *        generated settings page trustworthy.
 *  * WHERE: Returned by the registry IPC command; consumed by the Settings view
 *  *        and the dashboard shell.
 *  
 */
export type RegistrySnapshot = {
	capabilities: Capability[],
};

export type ResetSettingInput = {
	key: string,
};

export type SaveProfileInput = {
	profile: AppProfile,
};

export type SaveTextFileInput = {
	contents: string,
	/**  Offered in the dialog. The user may change it. */
	suggested_name: string,
};

export type SearchHistoryInput = {
	query: string,
	limit: number,
};

/**
 *  Correlation id shared by the database row, the tracing span, and the logs,
 *  so one string ties a user report to everything that happened.
 */
export type SessionId = string;

export type SessionIdInput = {
	id: SessionId,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SessionOutcome
 *  * WHAT:  How a session ended, as persisted. Cancelled sessions are absent by
 *  *        design — they are deleted, not marked.
 *  * WHY:   Orphaned exists only because a process can die mid-recording; it is
 *  *        written by recovery on the next launch, never by a transition.
 *  * WHERE: The `outcome` column on sessions; filtered by the History view.
 *  
 */
export type SessionOutcome = "DELIVERED" | "FAILED" | "ORPHANED";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SessionState
 *  * WHAT:  The live state of the one session that may exist at a time.
 *  * WHY:   Modelled as data-carrying variants so illegal states are
 *  *        unrepresentable — there is no way to be in CancelPending without a
 *  *        remaining time, and no way to be Failed without a reason.
 *  * WHERE: session/machine.rs owns every transition; the pill renders this and
 *  *        holds no state of its own.
 *  
 */
export type SessionState = 
/**  Nothing is happening. The pill is not on screen. */
{ kind: "IDLE" } | 
/**  Permission preflight passed, the device is opening. Sub-100ms normally. */
{ kind: "ARMING" } | { kind: "RECORDING"; elapsed_ms: number } | 
/**
 *  Escape armed. Audio is STILL being captured — nothing is torn down —
 *  which is what makes a second Escape resume with no gap.
 */
{ kind: "CANCEL_PENDING"; elapsed_ms: number; remaining_ms: number } | { kind: "FAILED"; code: ErrorCode; message: string };

/**  The pill's entire input. Emitted on every transition. */
export type SessionStateChanged = {
	state: SessionState,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SessionSummary
 *  * WHAT:  One persisted session as History and Stats read it.
 *  * WHY:   `raw_text` sits beside `final_text` so a bad result can be attributed
 *  *        to the model or to our own enhancement rules — without it that is
 *  *        guesswork.
 *  * WHERE: Produced by services/sessions.rs; consumed by the History view.
 *  
 */
export type SessionSummary = {
	id: SessionId,
	started_at_ms: number,
	ended_at_ms: number | null,
	outcome: SessionOutcome,
	duration_ms: number | null,
	language: string | null,
	engine_id: string,
	model_id: string,
	raw_text: string | null,
	final_text: string | null,
	word_count: number | null,
	app_bundle_id: string | null,
	delivery: DeliveryKind,
	error_code: string | null,
	/**
	 *  The plain-language reason, written once where the failure happened.
	 *  History renders this verbatim rather than mapping the code to its own
	 *  wording — see migration 002.
	 */
	error_message: string | null,
};

export type SetSettingInput = {
	key: string,
	value: SettingValue,
};

export type SettingChoice = {
	value: string,
	label: string,
	description: string | null,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SettingDef
 *  * WHAT:  One setting, fully described: how it renders, what it defaults to,
 *  *        and what it requires to be usable.
 *  * WHY:   `default` is typed as SettingValue and validated against `kind` at
 *  *        startup, so a mismatch is caught the first time the app runs rather
 *  *        than the first time a user opens that pane. `requires_engine` is what
 *  *        lets Settings explain that a language is unavailable on the selected
 *  *        engine instead of offering a control that silently fails at record
 *  *        time.
 *  * WHERE: Declared in registry/mod.rs; rendered by the SettingControl component;
 *  *        enforced on write by services/settings.rs.
 *  
 */
export type SettingDef = {
	/**
	 *  Globally unique, dotted, stable. This is the database key — renaming one
	 *  silently resets that setting for every existing user.
	 */
	key: string,
	label: string,
	description: string,
	section: SettingSection,
	kind: SettingKind,
	default: SettingValue,
	/**  Engine abilities without which this setting cannot do anything. */
	requires_engine: EngineFeature[],
	/**
	 * 
	 *      * OS grants without which this setting cannot do anything, whatever its
	 *      * value. A toggle that is ON while the permission behind it is missing is
	 *      * a control that lies: the user has said yes, the app agrees, and nothing
	 *      * happens. Declaring the dependency lets the UI say WHY instead — which is
	 *      * the same rule as `requires_engine`, applied to permissions.
	 *      
	 */
	requires_permission: OsPermission[],
	/**
	 *  Hidden behind a disclosure. For settings that exist to unstick a
	 *  specific machine, not ones people are expected to browse.
	 */
	advanced: boolean,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SettingKind, SettingChoice
 *  * WHAT:  Which control the frontend renders for a setting.
 *  * WHERE: One field on every SettingDef in the registry.
 *  
 */
export type SettingKind = { kind: "TOGGLE" } | { kind: "TEXT"; placeholder: string | null; max_len: number | null } | { kind: "NUMBER"; min: number | null; max: number | null; step: number | null; unit: string | null } | { kind: "CHOICE"; options: SettingChoice[] } | 
/**  A choice whose options are only knowable at runtime. */
{ kind: "DYNAMIC_CHOICE"; source: ChoiceSource } | { kind: "HOTKEY" };

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SettingSection
 *  * WHAT:  Which group of the Settings page a setting renders in.
 *  * WHY:   Grouping is presentation, but it belongs to the declaration — a
 *  *        setting that does not say where it goes forces the Settings view to
 *  *        keep its own ordering list, which is the exact duplication the
 *  *        registry exists to remove.
 *  * WHERE: On every SettingDef; used by the Settings view to build its sections.
 *  
 */
export type SettingSection = "RECORDING" | "TRANSCRIPTION" | "OUTPUT" | "VOCABULARY" | "PRIVACY" | "GENERAL";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SettingValue
 *  * WHAT:  A stored setting value, closed over the kinds above.
 *  * WHY:   Validating a value against its declared kind is only possible because
 *  *        both are typed; a bare JSON value would push that check to runtime in
 *  *        the frontend, where a bad value has already been saved.
 *  * WHERE: Stored by services/settings.rs; validated against the registry's
 *  *        SettingDef before a write is accepted.
 *  
 */
export type SettingValue = { type: "BOOL"; value: boolean } | { type: "NUMBER"; value: number | null } | { type: "TEXT"; value: string } | { type: "CHOICE"; value: string } | { type: "HOTKEY"; value: HotkeyBinding };

export type SettingsChanged = {
	/**  The setting that changed, or None when many changed at once. */
	key: string | null,
};

export type StartRecordingInput = {
	mode: RecordingMode,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: StatsSummary, ActivityDay, LanguageCount
 *  * WHAT:  Everything the Stats view shows, in one round trip.
 *  * WHY:   One shape rather than six commands, because the view renders all of it
 *  *        at once and six round trips would be six chances to render half a page.
 *  * WHERE: Produced by services/stats.rs; consumed by the Stats view.
 *  
 */
export type StatsSummary = {
	total_sessions: number,
	total_words: number,
	total_speaking_ms: number,
	sessions_this_week: number,
	words_this_week: number,
	today_sessions: number,
	today_words: number,
	/**  Words per minute actually spoken, measured. */
	speaking_wpm: number | null,
	/**  The user's typing baseline, from settings. The comparison, not a fact. */
	baseline_typing_wpm: number | null,
	/**  Time that would have been spent typing the same words, minus time spoken. */
	time_saved_ms: number,
	current_streak_days: number,
	activity: ActivityDay[],
	languages: LanguageCount[],
	latency: LatencySummary[],
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: TranscriptDelivered
 *  * WHAT:  A recording finished its journey — the text has been pasted or copied.
 *  * WHY:   Delivery no longer ends when the session state machine does, so the
 *  *        state stream can no longer tell anyone that words arrived. Anything
 *  *        that needs to know a delivery actually SUCCEEDED — as opposed to a
 *  *        recording merely having stopped — has to hear it here.
 *  *
 *  *        Onboarding is the case that proves it is needed rather than
 *  *        convenient: its hotkey step is deliberately completed by observing a
 *  *        real delivery rather than by a button the user clicks, because that is
 *  *        the only evidence that the shortcut registered, the microphone opened,
 *  *        the model ran AND the paste worked. Without this event that step would
 *  *        have had to settle for "a recording stopped", which is exactly the
 *  *        weaker assertion it was written to avoid.
 *  * WHERE: Emitted by session/delivery.rs at the end of every delivery.
 *  
 */
export type TranscriptDelivered = {
	word_count: number,
	delivery: DeliveryKind,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SettingsChanged
 *  * WHAT:  Announces that a setting was written or reset.
 *  * WHY:   More than one window reads settings — the dashboard, the pill and
 *  *        onboarding are separate documents with separate memory. Without this
 *  *        event each one keeps whatever it last fetched, so rebinding the hotkey
 *  *        in Settings leaves the pill rendering the old keycap indefinitely.
 *  *        Carrying the key lets a listener ignore changes it does not care
 *  *        about rather than refetching everything on every write.
 *  * WHERE: Emitted by ipc/commands/settings.rs after a successful write.
 *  
 * 
 *  * SOURCE OF TRUTH KEYWORDS: UpdateAvailable
 *  * WHAT:  A newer signed build exists.
 *  * WHY:   The `general.check_updates` setting promises a check "on launch and
 *  *        once a day", and until this event existed nothing delivered it —
 *  *        `check_for_update` and `install_update` were registered, exported, and
 *  *        called by nobody. A control that describes a schedule the app does not
 *  *        run is a control that lies.
 *  *
 *  *        Pushed rather than polled, like every other state in this app: the
 *  *        scheduler in bootstrap decides when to look, and the UI learns the
 *  *        answer whenever it arrives. A frontend that polled would have to own
 *  *        the schedule, and then the setting would describe one place while
 *  *        another did the work.
 *  * WHERE: Emitted by bootstrap's update scheduler; consumed by the dashboard,
 *  *        which offers the Update action that calls `install_update`.
 *  
 */
export type UpdateAvailable = {
	version: string,
	current_version: string,
	notes: string | null,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: UpdateCheck
 *  * WHAT:  What a check found: the feature is off, we are current, or there is a
 *  *        newer signed build.
 *  * WHY:   Three states rather than an `Option` plus a boolean, because "the
 *  *        user turned this off" is not the same answer as "there is nothing new"
 *  *        and the UI must not render them the same way. Collapsing them is how
 *  *        a disabled updater ends up quietly reporting "up to date" — a claim
 *  *        nobody checked.
 *  * WHERE: Returned by check_for_update; rendered by the Settings view.
 *  
 */
export type UpdateCheck = 
/**  `general.check_updates` is off. No request was made. */
{ kind: "DISABLED" } | { kind: "UP_TO_DATE"; current_version: string } | { kind: "AVAILABLE"; version: string; current_version: string; 
/**  Release notes, when the release carries them. */
notes: string | null; 
/**  RFC 3339, as published. None when the release omits it. */
published_at: string | null };

export type UpdateDictionaryEntryInput = {
	id: DictionaryId,
	replacement: string,
	match_kind: MatchKind,
	enabled: boolean,
};

export type WipeResult = {
	sessions_deleted: number,
	dictionary_entries_deleted: number,
	settings_deleted: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

