# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: WebProdigies.HushWrite
PackageVersion: 0.1.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - silent
  - interactive
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://github.com/alexgutscher26/HushWrite/releases/download/v0.1.0/HushWrite_0.1.0_x64-setup.exe
    InstallerSha256: D227D0CE2348AD678D6AE61EE4936AF3C2BE85EE9B1B5244BA5B7D022024AA4C
    ProductCode: HushWrite
ManifestType: installer
ManifestVersion: 1.6.0
