/*!
 * SOURCE OF TRUTH KEYWORDS: settings_capability, CapabilityKey::Settings
 * WHAT:  Declares Output and General settings capability (paste, cleanup, pill, launch at login).
 * WHERE: Consumed by registry/capabilities/mod.rs.
 */

use super::helpers::{
    advanced, choice, metric, needs_permission, number, string_setting, text, toggle,
};
use crate::ports::permissions::OsPermission;
use crate::registry::capability::{Capability, CapabilityKey, NavDef, SettingSection};
use crate::registry::keys;
use crate::types::LatencyStage;

pub fn settings_capability() -> Capability {
    Capability {
        key: CapabilityKey::Settings,
        name: text("Output"),
        description: text("What happens to your words once they are transcribed."),
        // Accessibility is NOT required: without it delivery degrades to
        // clipboard-only, which is a supported outcome rather than a failure.
        requires: vec![],
        engine_needs: vec![],
        nav: Some(NavDef {
            label: text("Settings"),
            route: text("settings"),
            icon: text("Settings"),
            order: 30,
        }),
        hotkey: None,
        metrics: vec![
            metric(LatencyStage::ClipboardWrite, "Clipboard", false),
            metric(LatencyStage::Inject, "Paste", false),
        ],
        settings: vec![
            needs_permission(
                toggle(
                    keys::AUTO_PASTE,
                    "Paste automatically",
                    "Paste into whatever had focus. Turn this off to only copy to the clipboard.",
                    SettingSection::Output,
                    true,
                ),
                OsPermission::Accessibility,
            ),
            needs_permission(
                toggle(
                    keys::RESTORE_CLIPBOARD,
                    "Restore my clipboard",
                    "Put back what was on the clipboard after pasting. Turn this off if pastes arrive empty in a particular app.",
                    SettingSection::Output,
                    true,
                ),
                OsPermission::Accessibility,
            ),
            advanced(number(
                keys::PASTE_DELAY_MS,
                "Paste delay",
                "How long to wait after writing the clipboard before pasting. Raise it if an app pastes stale text.",
                SettingSection::Output,
                (0.0, 500.0, 5.0),
                Some("ms"),
                40.0,
            )),
            advanced(number(
                keys::CLIPBOARD_RESTORE_DELAY_MS,
                "Clipboard restore delay",
                "How long to wait after pasting before restoring the clipboard.",
                SettingSection::Output,
                (0.0, 1000.0, 10.0),
                Some("ms"),
                150.0,
            )),
            toggle(
                keys::CAPITALISE_SENTENCES,
                "Capitalise sentences",
                "Start each sentence with a capital letter.",
                SettingSection::Output,
                true,
            ),
            toggle(
                keys::NORMALISE_PUNCTUATION,
                "Tidy punctuation",
                "Normalise spacing, quotes and terminal punctuation.",
                SettingSection::Output,
                true,
            ),
            toggle(
                keys::STRIP_FILLERS,
                "Remove filler words",
                "Drop “um”, “uh”, “you know” and similar so speech reads like writing.",
                SettingSection::Output,
                false,
            ),
            toggle(
                keys::SPOKEN_COMMANDS,
                "Spoken formatting",
                "Turn “new line”, “new paragraph”, “comma” and “period” into the thing you said.",
                SettingSection::Output,
                true,
            ),
            toggle(
                keys::APPLY_CORRECTIONS,
                "Apply spoken corrections",
                "When you correct yourself out loud — \u{201c}Tuesday, sorry, I meant Wednesday\u{201d} — keep only the correction. It matches spoken phrases like \u{201c}I meant\u{201d} and \u{201c}make that\u{201d}; it does not rewrite your wording.",
                SettingSection::Output,
                false,
            ),
            toggle(
                keys::EXPAND_ABBREVIATIONS,
                "Expand common abbreviations",
                "Expand spoken Latin and common abbreviations (e.g. “eg” → “e.g.”, “ie” → “i.e.”, “etc” → “etc.”, “vs” → “vs.”).",
                SettingSection::Output,
                true,
            ),
            advanced(string_setting(
                keys::DISABLED_ABBREVIATIONS,
                "Disabled abbreviations",
                "Comma-separated list or JSON array of abbreviations to leave unexpanded (e.g. “eg, vs”).",
                SettingSection::Output,
                Some("eg, vs"),
                "",
            )),
            toggle(
                keys::NORMALISE_NUMBERS,
                "Normalize numbers and currency",
                "Convert spoken numbers, ordinals, and currency into digits and symbols (e.g. “forty two” → 42, “third” → 3rd, “twenty dollars” → $20).",
                SettingSection::Output,
                true,
            ),
            toggle(
                keys::NORMALISE_URLS_AND_PATHS,
                "Normalize URLs, emails and paths",
                "Format spoken web links, email addresses, and filesystem paths (e.g. “https colon slash slash github dot com” → https://github.com).",
                SettingSection::Output,
                true,
            ),
            toggle(
                keys::CODE_MODE,
                "Code mode identifier casing",
                "Automatically detect compound words and format them into the active code casing style.",
                SettingSection::Output,
                false,
            ),
            choice(
                keys::CODE_CASING_STYLE,
                "Code casing style",
                "Target identifier style used when code mode is active.",
                SettingSection::Output,
                &[
                    ("camel", "camelCase", "Lower camel case (e.g. userProfileComponent)."),
                    ("pascal", "PascalCase", "Upper camel case (e.g. UserProfileComponent)."),
                    ("snake", "snake_case", "Underscore separated lowercase (e.g. user_profile_component)."),
                    ("screaming_snake", "CONSTANT_CASE", "All uppercase underscore separated (e.g. USER_PROFILE_COMPONENT)."),
                    ("kebab", "kebab-case", "Dash separated lowercase (e.g. user-profile-component)."),
                ],
                "camel",
            ),
            toggle(
                keys::LLM_CLEANUP_ENABLED,
                "On-device smart cleanup (LLM)",
                "Run dictation through local llama-cpp-2 GGUF models for intelligent filler removal and punctuation polishing.",
                SettingSection::Output,
                false,
            ),
            choice(
                keys::LLM_MODEL,
                "LLM cleanup & transform model",
                "Choose the on-device language model for smart cleanup and conversational transforms.",
                SettingSection::Output,
                &[
                    ("auto", "Automatic (Hardware-Optimized)", "Auto-selects optimal model and quantization tier based on hardware profile."),
                    ("qwen2.5-1.5b-instruct-q4_k_m", "Qwen 2.5 1.5B (Q4_K_M - Fast CPU)", "Sub-second filler removal and 99-language formatting on laptops."),
                    ("qwen2.5-1.5b-instruct-q5_k_m", "Qwen 2.5 1.5B (Q5_K_M - GPU)", "High-fidelity 5-bit cleanup on dedicated GPU/workstation."),
                    ("phi-3.5-mini-instruct-q4_k_m", "Phi-3.5 Mini (Q4_K_M - Fast CPU)", "Deep tone rewriting and voice transforms on CPU."),
                    ("phi-3.5-mini-instruct-q6_k", "Phi-3.5 Mini (Q6_K - High Precision)", "6-bit precision reasoning for executive document synthesis on GPU."),
                ],
                "auto",
            ),
            toggle(
                keys::LLM_AUTO_QUANTIZATION,
                "Auto-select Q4_K_M for CPU laptops",
                "Automatically switch to Q4_K_M quantization on CPU-bound machines to maintain sub-second latency and minimal RAM footprint.",
                SettingSection::Output,
                true,
            ),
            toggle(
                keys::VOICE_TRANSFORMS_ENABLED,
                "Conversational voice transforms",
                "Speak commands like “Hey HushWrite, make that formal” or “make this concise” to transform text on-device.",
                SettingSection::Output,
                true,
            ),
            advanced(string_setting(
                keys::VOICE_TRANSFORM_TRIGGER,
                "Voice transform trigger phrase",
                "Spoken prefix used while dictating to transform tone or formatting (e.g., “Hey HushWrite, make that formal: ...”).",
                SettingSection::Output,
                Some("Hey HushWrite"),
                "Hey HushWrite",
            )),
            advanced(string_setting(
                keys::CUSTOM_SYSTEM_PROMPT,
                "Custom system prompt",
                "Custom instructions injected into the local LLM post-processing pass for domain jargon and stylistic guidelines.",
                SettingSection::Output,
                Some("e.g. Always format technical terms in backticks"),
                "",
            )),
            toggle(
                keys::LAUNCH_AT_LOGIN,
                "Launch at login",
                "Start HushWrite automatically when you log in.",
                SettingSection::General,
                false,
            ),
            number(
                keys::BASELINE_WPM,
                "Your typing speed",
                "Used to work out how much time dictation has saved you.",
                SettingSection::General,
                (10.0, 200.0, 1.0),
                Some("wpm"),
                40.0,
            ),
            choice(
                keys::OVERLAY_STYLE,
                "Overlay style",
                "Choose how the recording indicator looks on screen during dictation.",
                SettingSection::Overlay,
                &[
                    ("floating_pill", "Floating Pill", "Classic floating glass pill with live waveform and status."),
                    ("notch", "Top Notch", "Dynamic island bar hugging the top screen edge."),
                    ("notch_slim_band", "Notch Slim Band", "Minimal glowing accent band beside the notch."),
                    ("notch_drop_pill", "Notch Drop Pill", "Floating pill anchored and dropping just below the notch."),
                    ("none", "None (Stealth)", "Completely hidden overlay for silent indicator-free dictation."),
                ],
                "floating_pill",
            ),
            choice(
                keys::ACCENT_COLOR,
                "Accent colour",
                "Color theme for the overlay glow, waveform visualizer, and notch borders.",
                SettingSection::Overlay,
                &[
                    ("monochrome", "Monochrome", "Clean white glass aesthetic."),
                    ("amber", "Electric Amber", "Vibrant warm gold and amber glow."),
                    ("purple", "Cyber Violet", "Deep futuristic neon purple."),
                    ("cyan", "Neon Cyan", "Luminescent ocean sky cyan."),
                    ("emerald", "Emerald Mint", "Crisp radiant emerald mint green."),
                    ("rose", "Rose Quartz", "Warm glowing ruby and rose pink."),
                    ("sunset", "Sunset Flare", "Dynamic gradient solar flare orange."),
                    ("aurora", "Aurora Green", "Ethereal northern lights green."),
                ],
                "monochrome",
            ),
            choice(
                keys::PILL_ANCHOR,
                "Floating pill position",
                "Screen anchor point for the floating pill overlay.",
                SettingSection::Overlay,
                &[
                    ("top_left", "Top Left", "Pinned to the top left corner."),
                    ("top_center", "Top Center", "Centered at the top of the display."),
                    ("top_right", "Top Right", "Pinned to the top right corner."),
                    ("center_left", "Center Left", "Centered along the left screen edge."),
                    ("center", "Center", "Directly in the center of the active display."),
                    ("center_right", "Center Right", "Centered along the right screen edge."),
                    ("bottom_left", "Bottom Left", "Pinned to the bottom left corner."),
                    ("bottom_center", "Bottom Center", "Centered at the bottom of the display."),
                    ("bottom_right", "Bottom Right", "Pinned to the bottom right corner."),
                ],
                "bottom_center",
            ),
            number(
                keys::PILL_OPACITY,
                "Pill opacity",
                "Adjust background opacity of the floating pill from 30% to 100%.",
                SettingSection::Overlay,
                (30.0, 100.0, 5.0),
                Some("%"),
                100.0,
            ),
            toggle(
                keys::PILL_COMPACT,
                "Compact pill mode",
                "Show a minimal icon-only pill indicator while dictating.",
                SettingSection::Overlay,
                false,
            ),
            toggle(
                keys::CONFETTI_EFFECT,
                "Celebration confetti",
                "Burst celebratory particle confetti when transcription successfully finishes and pastes.",
                SettingSection::Overlay,
                true,
            ),
            toggle(
                keys::SHOW_TRAY_ICON,
                "Show menu bar / tray icon",
                "Show the HushWrite icon in your system tray / menu bar. When turned off and overlay is set to None, recording has zero visible indicators.",
                SettingSection::Overlay,
                true,
            ),
            toggle(
                keys::CHECK_UPDATES,
                "Check for updates",
                "Check for a new version on launch and once a day. This is the only network request HushWrite makes after setup.",
                SettingSection::General,
                true,
            ),
            choice(
                keys::UPDATE_CHANNEL,
                "Update channel",
                "Select which update channel HushWrite checks for new desktop releases.",
                SettingSection::General,
                &[
                    ("stable", "Stable", "Official thoroughly tested production releases."),
                    ("beta", "Beta", "Pre-release builds with early access to new models and features."),
                ],
                "stable",
            ),
        ],
    }
}
